runtime: python39
service: poupai-frontend

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /(.*)
  static_files: \1
  upload: .*

automatic_scaling:
  min_instances: 0
  max_instances: 1
